# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 189dfcbab82883155b309d65fe6c4c0c2b71bd513ddea41e1875a116cc0797c26d31af8436605f5dba01366fdff2c72994703e0a5fb56fdd18b243cbc81aa65c

test:
  secret_key_base: 6a7bddd17b3ed820bf574ecf27d701f104759c04baba777123c48cfa32fcb8d3735805760e567b9934266e513bfef13fa308c237c51b0d9cb5219df4dbb59c69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
